version: "3.9"

services:
  spark-hudi:
    build: ./dockerfiles/hudi
    environment:
      # SPARK_HOME is not just used in the dockerfile, it's for Spark itself,
      # and it needs to be set to where Spark is set up in the base image
      SPARK_HOME: /opt/spark
      # SPARK_MASTER_NAME is the domain that Spark is running on, which should
      # match the docker compose service name
      SPARK_MASTER_NAME: spark-hudi
      SPARK_APPLICATIONS_HOME: /opt/spark-apps
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_LOG: /spark/logs
    ports:
      - "5555:7077"

  dbt-spark:
    build:
      context: ./dbt_spark_example/
      dockerfile: ../dockerfiles/dbt/Dockerfile
    volumes:
      - ./dbt_spark_example/:/usr/src/app
    # command: sleep infinity
